# Generated by Django 3.1.7 on 2021-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210516_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ebay_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flipkart_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
